---
title: "A2_Group5"
author: "Mirre Dona (6156630)"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries
```{r}
library(ISLR)
library(tidyverse)
library(haven)
library(readr)
library(dplyr)
library(magrittr) #to use piping %>% 
library(class) #knn()
library(MASS) #lda()
library(splines) #bs() ns()
library(cowplot) #plot_grid()
library(psych) #describeBy()
#tree based methods
library(rpart)
library(rpart.plot)
library(randomForest)
library(pROC) #ROC curve
library(caret) #bagging,  boosting, rf
library(mice)

```


#Import dataset
```{r}
sleepdata <- read.csv('data/Sleep_health_and_lifestyle_dataset.csv')
View(sleepdata)
```

#Data cleaning
```{r}
md.pattern(sleepdata)
```
There is no missing data in this dataset!

Let's convert the variables to the right type for exploration and prediction later on.
```{r}
#check how many unique values of occupation, to see if it makes sense to convert to factor, or if there are too many unique values
unique(sleepdata$Occupation)
```


```{r}
sleepdata %<>% 
  mutate(Gender   = as.factor(Gender),
         Occupation = as.factor(Occupation),
         BMI.Category = as.factor(BMI.Category)) %>% 
  select(-Person.ID)
```

